### ISSUE TITLE
Remove css from user website

### ISSUE THREAD

**Issue by eerison** [shield-wall/myprofile#303]
for now we are using many css to user's website [example](https://www.myprofile.pro/eerison)
the idea is use only [bulma](https://bulma.io) for this page.

**Comment by moisesgui** [comment]
I can do this, but would it be just to remove css files that are unused?

**Comment by eerison** [comment]
in this [page](https://myprofile.pro/eerison)  there are some CSS files, the idea is to remove all CSS write in the project and use only bulma.io

**Comment by moisesgui** [comment]
oks understand
